repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: 'wsd/'
        args: [--line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: 'wsd/'
        args: [--profile=black, -m=3, -l=120]

  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.3.0
    hooks:
      - id: unimport
        files: 'wsd/'
        args: [--remove, --include-star-import]

  - repo: local
    hooks:
      - id: migration-check
        name: migration-check
        entry: scripts/pre-commit/migration_check.sh
        language: script

  - repo: local
    hooks:
      - id: lint-frontend
        name: lint-frontend
        entry: scripts/pre-commit/lint_frontend.sh
        language: script
